-- MySQL Script generated by MySQL Workbench
-- Tue Jan 24 16:46:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema module3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `module3`;

-- -----------------------------------------------------
-- Schema module3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `module3` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `module3`;

-- -----------------------------------------------------
-- Table `module3`.`gift_certificates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `module3`.`gift_certificates`;

CREATE TABLE IF NOT EXISTS `module3`.`gift_certificates`
(
    `id`               INT            NOT NULL AUTO_INCREMENT,
    `name`             VARCHAR(45)    NOT NULL,
    `description`      VARCHAR(150)   NULL DEFAULT NULL,
    `price`            DECIMAL(10, 2) NOT NULL,
    `duration`         TINYINT        NOT NULL,
    `create_date`      VARCHAR(40)    NOT NULL,
    `last_update_date` VARCHAR(40)    NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 1
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `module3`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `module3`.`tags`;

CREATE TABLE IF NOT EXISTS `module3`.`tags`
(
    `id`   INT         NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 1
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `module3`.`gift_certificates_has_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `module3`.`gift_certificates_has_tags`;

CREATE TABLE IF NOT EXISTS `module3`.`gift_certificates_has_tags`
(
    `gift_certificate_id` INT NOT NULL,
    `tag_id`              INT NOT NULL,
    PRIMARY KEY (`gift_certificate_id`, `tag_id`),
    INDEX `fk_gift_certificate_has_tag_tag1` (`tag_id` ASC),
    CONSTRAINT `fk_gift_certificate_has_tag_gift_certificate`
        FOREIGN KEY (`gift_certificate_id`)
            REFERENCES `module3`.`gift_certificates` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `fk_gift_certificate_has_tag_tag1`
        FOREIGN KEY (`tag_id`)
            REFERENCES `module3`.`tags` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `module3`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `module3`.`users`;

CREATE TABLE IF NOT EXISTS `module3`.`users`
(
    `id`   INT         NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `module3`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `module3`.`orders`;

CREATE TABLE IF NOT EXISTS `module3`.`orders`
(
    `id`                   INT            NOT NULL,
    `price`                DECIMAL(10, 2) NOT NULL,
    `purchase_date`        VARCHAR(40)    NOT NULL,
    `users_id`             INT            NOT NULL,
    `gift_certificates_id` INT            NOT NULL,
    PRIMARY KEY (`id`, `users_id`, `gift_certificates_id`),
    INDEX `users_id` (`users_id` ASC) VISIBLE,
    INDEX `gift_certificates_id` (`gift_certificates_id` ASC) VISIBLE,
    CONSTRAINT `orders_ibfk_1`
        FOREIGN KEY (`users_id`)
            REFERENCES `module3`.`users` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `orders_ibfk_2`
        FOREIGN KEY (`gift_certificates_id`)
            REFERENCES `module3`.`gift_certificates` (`id`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
